config/routes.rb
Rails.application.routes.draw do
  devise_for :clothes
  # 顧客用
# URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  root to: "homes#top"
  namespace :public do
    
    
    get "/users/show" => "users#show"
    get "/users/show/eidt" => "users#edit"
    # patch  '/users/withdraw' => 'users#withdraw'
    # タグの検索で使用する
    get "search_tag" => "posts#search_tag"
    get "search" => "posts#search"
    # get "/post/search_tag/:id" => "posts#search_tag"
    resources :clothes, only: [:create, :index, :show]
    resources :users, only: [:destroy, :update] do
      member do
        get :favorites
      end
    end
    # get "/piblic/posts/show" => "posts#show"
    resources :posts, only: [:index, :create, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create]
      # resources :tags, only: [:create]
    end
    
  end
  # 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    get "/homes" => "homes#top"
    resources :clothes, only: [:new, :create, :index, :show, :edit, :update]
    resources :users, only: [:index, :show]
    resources :posts, only: [:destroy, :index, :show] do
      resource :comments, only: [:destroy]
      
    end
  end
  
end

app/models/post.rb
class Post < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 belongs_to :clothe
 belongs_to :user
 has_many :comment, dependent: :destroy
 has_many :favorite, dependent: :destroy

 has_many :post_tags, dependent: :destroy
 has_many :tags, through: :post_tags

 attr_accessor :post_tags_attributes

before_validation :tags_count_check
after_save :tag_set

validates :text, presence: true

def tags_count_check
  tag_names = self.post_tags_attributes.values.map{|o|o['tag_name']}.reject(&:blank?)
  #byebug
  if tag_names.blank?
    errors.add(:base, "タグは1つ以上入れてください")
  end
end

def tag_set
  old_tag_names = self.tags.pluck(:name)
  tag_names = self.post_tags_attributes.values.map{|o|o['tag_name']}.reject(&:blank?)
  reject_tag_names = old_tag_names - tag_names
  new_tag_names = tag_names - old_tag_names

  new_tag_names.each do |tag_name|
    tag = Tag.find_or_create_by(name: tag_name)
    self.post_tags.find_or_create_by(tag_id: tag.id)
  end
  reject_tag_names.each do |tag_name|
    tag = Tag.find_by(name: tag_name)
    if tag.post_tags.size <= 1
      tag.destroy if tag
    else
      post_tag = tag.post_tags.find_by(post_id: self.id)
      post_tag.destroy if post_tag
    end
  end
end

 #accepts_nested_attributes_for :tags, allow_destroy: true

 # before_validation :downcase_tag_name
 # validates :tag_name, presence: true, uniqueness: { case_sensitive: false }

 def favorited_by?(user)
   favorite.exists?(user_id: user.id)
 end

 #検索メソッド、タイトルと内容をあいまい検索する
 def self.posts_serach(search)
   Post.where('text LIKE ?', "%#{search}%")
 end

 def save_posts(tag_list)
  # タグが存在していれば、タグの名前を配列として全て取得
   current_tags = self.tag.pluck(:tag_name) unless self.tag.nil?
  # 現在取得したタグから送られてきたタグを除いてoldtagとする
   old_tags = current_tags - tag
   # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
   new_tags = tag - current_tags


   # 古いタグを消す
   old_tags.each do |old_name|
     self.tags.delete Tag.find_by(tag_name:old_name)
   end

   # 新しいタグを保存
   new_tags.each do |new_name|
     post_tag = Tag.find_or_create_by(tag_name:new_name)
     self.tag << tag
   end
 end

 def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("text LIKE?","#{word}")
    elsif search == "partial_match"
      @post = Post.where("text LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
before_action :authenticate_admin!
  def show
    @post = Post.find(params[:id])
    @comments = @post.comment.all
    # @user = User.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to admin_users_path
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
      <%= @user.name%>さんのページ
      <table cellpadding="10">
        <thead>
          <tr>
            <th>気温</th>
            <th>投稿内容</th>
            <th>投稿日</th>
          </tr>
        </thead>
        <% @posts.each do |post| %>
        <tbody>
          <tr>
            <td><%= post.clothe.celsius %></td>
            <td width="350px"><%= post.text %></td>
            <td><%= post.created_at.strftime('%Y/%m/%d') %></td>
            <td><%= link_to "削除する", public_post_path(post.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
          </tr>
        </tbody>
        <% end %>
      </table>

app/views/admin/posts/show.html.erb
<div class="container py-3">
  <div class="row py-3">
    <h2>コメント一覧</h2>
  </div>
  
  <div class="row py-3">
    <div class="col-md-2">
      <%= image_tag @post.user.get_image(100,100), size: "130x130" %><br>
      <%= @post.user.name %>
    </div>
    
    <div class="col-md-3">
      <table>
        <tr>
          <td><%= @post.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <td><%= @post.clothe.celsius %></td>
        </tr>
        <tr>
          <td>
            <%= @post.text %><br>
            <% @post.tags.each do |tag| %>
            #<%= tag.name %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
    
    <div class="col-md-5">
      <h5>コメント（全<%= @comments.count %>件）</h5>
      <table class="table" cellpadding="5">
        <% @comments.each do |comment| %>
        <tr>
          <th width="110"><%= comment.user.name %></th>
          <td><%= comment.comment_text %></td>
          <td><%= link_to "削除する", admin_post_comments_path(comment.post.id,comment.id), method: :delete, "data-confirm" => "本当に削除しますか？" , class:'btn btn-sm btn-danger'%></td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
  
  <div class="row py-3">
    <div class="col-md-5">
      <%= link_to "≪ユーザー詳細へ",admin_user_path(@post.id) %>
    </div>
  </div>
</div>