config/routes.rb
Rails.application.routes.draw do
  devise_for :clothes
  # 顧客用
# URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  root to: "homes#top"
  namespace :public do
    
    
    get "/users/show" => "users#show"
    get "/users/show/eidt" => "users#edit"
    # patch  '/users/withdraw' => 'users#withdraw'
    # タグの検索で使用する
    get "search_tag" => "posts#search_tag"
    get "search" => "posts#search"
    # get "/post/search_tag/:id" => "posts#search_tag"
    resources :clothes, only: [:create, :index, :show]
    resources :users, only: [:destroy, :update] do
      member do
        get :favorites
      end
    end
    # get "/piblic/posts/show" => "posts#show"
    resources :posts, only: [:index, :create, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create]
      # resources :tags, only: [:create]
    end
    
  end
  # 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    get "/homes" => "homes#top"
    resources :clothes, only: [:new, :create, :index, :show, :edit, :update]
    resources :users, only: [:index, :show]
    resources :posts, only: [:destroy, :index, :show] do
      resource :comments, only: [:destroy]
      
    end
  end
  
end

app/models/clothe.rb
class Clothe < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
         
  has_one_attached :image
  
  validates :celsius, presence: true
  validates :introduction, presence: true
  validates :image, presence: true
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
end

app/controllers/admin/clothes_controller.rb
class Admin::ClothesController < ApplicationController
before_action :authenticate_admin!
  def new
    @clothe = Clothe.new
  end

  def index
    @clothes = Clothe.all
  end

  def show
    @clothe = Clothe.find(params[:id])
  end

  def create
    # byebug
    @clothe = Clothe.new(clothe_params)
    if @clothe.save
      redirect_to admin_clothe_path(@clothe.id)
    else
      render :new
    end
  end

  def edit
    @clothe = Clothe.find(params[:id])
  end

  def update
    @clothe = Clothe.find(params[:id])
    @clothe.update(clothe_params)
    redirect_to admin_clothe_path(@clothe.id)
  end

  private

    def clothe_params
      params.require(:clothe).permit(:image, :celsius, :introduction)
    end

end

app/helpers/admin/clothes_helper.rb
module Admin::ClothesHelper
end

app/views/admin/clothes/edit.html.erb
<div class="container py-3">
  <div class="row py-3">
    <h2>服装編集</h2>
  </div>
  <div class="row justify-content-center">
    <%= form_with model: @clothe, url: admin_clothe_path, method: :patch do |f| %>
    <table cellpadding="7">
      <tr>
        <th>画像</th>
        <td><%= f.file_field :image, accept: "image/*" %></td>
      </tr>
      <tr>
        <th>気温</th>
        <td><%= f.select :celsius,["30℃~","25~30℃","20~25℃","16~20℃","12~16℃","8~12℃","5~8℃","5℃未満"] %></td>
      </tr>
      <tr>
        <th>説明文</th>
        <td><%= f.text_area :introduction, :size =>"53x10"%></td>
      </tr>
    </table>
  </div>
  <div class="row justify-content-center py-5">
    <%= f.submit "変更する" %>
    <% end %>
  </div>
</div>

app/views/admin/clothes/index.html.erb
<div class="container py-3">
  <div class="row py-3">
    <div class="col-md-2 offset-md-2">
      <h2>服装一覧</h2>
    </div>
    <div class="col-md-2 offset-md-5">
      <%= link_to "+服装を追加する", new_admin_clothe_path %>
    </div>
  </div>
  <div class="col-md-9 offset-md-1 p-3">
    <div class="row">
      <% @clothes.each do |clothe| %>
      <div class="col-md-2">
        <%= link_to admin_clothe_path(clothe.id) do %>
        <%= image_tag clothe.get_image(100,100), size: "70x250" %><br>
        <% end %>
        <%= clothe.celsius %><br>
        <%= clothe.introduction.truncate(13) %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/clothes/new.html.erb
<div class="container py-3">
  <div class="row py-3">
    <h2>服装登録</h2>
  </div>
  
  <% if @clothe.errors.any? %>
  <%= @clothe.errors.count %>件のエラーが発生しました
  <ul>
    <% @clothe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
  
  <div class="row justify-content-center">
    <%= form_with model:@clothe, url: admin_clothes_path do |f| %>
    <table cellpadding="7">
      <tr>
        <th><h5>画像</h5></th>
        <td><%= f.file_field :image, accept: "image/*" %></td>
      </tr>
      <tr>
        <th><h5>気温</h5></th>
        <td>
          <%= f.select :celsius,["30~℃","25~30℃","20~25℃","16~20℃","12~16℃","8~12℃","5~8℃","5℃未満"] %>
        </td>
      </tr>     
      <tr>
        <th><h5>説明文</h5></th>
        <td><%= f.text_area :introduction, :size=>"52x10" %></td>
      </tr>
    </table>
  </div>
  <div class="row justify-content-center py-5">
    <%= f.submit '登録する' %>
    <% end %>
  </div>
</div>

app/views/admin/clothes/show.html.erb
<div class="container py-3">
  <div class="row py-3">
    <h2>服装詳細</h2>
  </div>
  <div class="row justify-content-center py-3">
    <div class="col-md-2">
    <%= image_tag @clothe.get_image(100,100), size: "100x350" %>
    </div>
    <div class="col-md-5">
      <div class="py-3">
        <%= @clothe.celsius %><br>
        <%= @clothe.introduction %>
      </div>
      <%= link_to "編集する", edit_admin_clothe_path %>
    </div>
  </div>
</div>