config/routes.rb
Rails.application.routes.draw do
  devise_for :clothes
  # 顧客用
# URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  root to: "homes#top"
  namespace :public do
    
    
    get "/users/show" => "users#show"
    get "/users/show/eidt" => "users#edit"
    # patch  '/users/withdraw' => 'users#withdraw'
    # タグの検索で使用する
    get "search_tag" => "posts#search_tag"
    get "search" => "posts#search"
    # get "/post/search_tag/:id" => "posts#search_tag"
    resources :clothes, only: [:create, :index, :show]
    resources :users, only: [:destroy, :update] do
      member do
        get :favorites
      end
    end
    # get "/piblic/posts/show" => "posts#show"
    resources :posts, only: [:index, :create, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create]
      # resources :tags, only: [:create]
    end
    
  end
  # 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    get "/homes" => "homes#top"
    resources :clothes, only: [:new, :create, :index, :show, :edit, :update]
    resources :users, only: [:index, :show]
    resources :posts, only: [:destroy, :index, :show] do
      resource :comments, only: [:destroy]
      
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :image
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
  def user_status
    if is_deleted == true
      "✕"
    else
      "〇"
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.page(params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page])
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/index.html.erb
<div class="container py-3">
  <h4><%= flash[:notice] %></h4>
  <div class="row py-3">
    <h2>ユーザー一覧</h2><br>
  </div>
  <div class="row justify-content-center py-3">
    <table  class="table" cellpadding="10">
      <thead align="center">
        <tr>
          <th>ユーザーID</th>
          <th>ユーザー名</th>
          <th>メールアドレス</th>
        </tr>
      </thead>
      <tbody align="center">
        <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td>
            <%= link_to admin_user_path(user.id) do %>
            <%= user.name %>
            <% end %>
          </td>
          <td><%= user.email %></td>
        </tr>
        <% end %>
        <%= paginate @users %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 py-5">
      <h2>ユーザー詳細</h2>
      <div class="row p-3 mx-3">
      <%= image_tag @user.get_image(100,100), size: "150x150" %>
      </div>
      <table cellpadding="5">
        <tr>
          <th>会員ID</th>
        </tr>
        <tr>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <th>ユーザーネーム</th>
        </tr>
        <tr>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
        </tr>
        <tr>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th>投稿数</th>
        </tr>
        <tr>
          <td>
          <%= @posts.count %>
        </td>
        </tr>
      </table>
      <%= link_to "≪ユーザー一覧へ", admin_users_path %>
    </div>
    <div class="col-md-7 py-5">
    <table cellpadding="10">
      <thead>
        <tr>
          <th>気温</th>
          <th>投稿内容</th>
          <th>投稿日</th>
        </tr>
      </thead>
      <% @posts.each do |post| %>
      <tbody>
        <tr>
          <td><%= post.clothe.celsius %></td>
          <td width="350px">
            <%= link_to admin_post_path(post.id) do %>
            <%= post.text %>
            <% end %>
          </td>
          <td><%= post.created_at.strftime('%Y/%m/%d') %></td>
          <td><%= link_to "削除する", admin_post_path(post.id), method: :delete, "data-confirm" => "本当に削除しますか？" , class:'btn btn-sm btn-danger'%></td>
        </tr>
      </tbody>
      <% end %>
      <%= paginate @posts %>
    </table>
  </div>
</div>