config/routes.rb
Rails.application.routes.draw do
  devise_for :clothes
  # 顧客用
# URL /users/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  root to: "homes#top"
  namespace :public do
    
    
    get "/users/show" => "users#show"
    get "/users/show/eidt" => "users#edit"
    # patch  '/users/withdraw' => 'users#withdraw'
    # タグの検索で使用する
    get "search_tag" => "posts#search_tag"
    get "search" => "posts#search"
    # get "/post/search_tag/:id" => "posts#search_tag"
    resources :clothes, only: [:create, :index, :show]
    resources :users, only: [:destroy, :update] do
      member do
        get :favorites
      end
    end
    # get "/piblic/posts/show" => "posts#show"
    resources :posts, only: [:index, :create, :show, :destroy] do
      resource :favorites, only: [:create, :destroy]
      resources :comments, only: [:create]
      # resources :tags, only: [:create]
    end
    
  end
  # 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    get "/homes" => "homes#top"
    resources :clothes, only: [:new, :create, :index, :show, :edit, :update]
    resources :users, only: [:index, :show]
    resources :posts, only: [:destroy, :index, :show] do
      resource :comments, only: [:destroy]
      
    end
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clothe.rb
class Clothe < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
         
  has_one_attached :image
  
  validates :celsius, presence: true
  validates :introduction, presence: true
  validates :image, presence: true
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
end

app/models/comment.rb
class Comment < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  belongs_to :post
  belongs_to :user
  
  validates :comment_text, presence: true
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: {scope: :post_id}

end

app/models/post.rb
class Post < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 belongs_to :clothe
 belongs_to :user
 has_many :comment, dependent: :destroy
 has_many :favorite, dependent: :destroy

 has_many :post_tags, dependent: :destroy
 has_many :tags, through: :post_tags

 attr_accessor :post_tags_attributes

before_validation :tags_count_check
after_save :tag_set

validates :text, presence: true

def tags_count_check
  tag_names = self.post_tags_attributes.values.map{|o|o['tag_name']}.reject(&:blank?)
  #byebug
  if tag_names.blank?
    errors.add(:base, "タグは1つ以上入れてください")
  end
end

def tag_set
  old_tag_names = self.tags.pluck(:name)
  tag_names = self.post_tags_attributes.values.map{|o|o['tag_name']}.reject(&:blank?)
  reject_tag_names = old_tag_names - tag_names
  new_tag_names = tag_names - old_tag_names

  new_tag_names.each do |tag_name|
    tag = Tag.find_or_create_by(name: tag_name)
    self.post_tags.find_or_create_by(tag_id: tag.id)
  end
  reject_tag_names.each do |tag_name|
    tag = Tag.find_by(name: tag_name)
    if tag.post_tags.size <= 1
      tag.destroy if tag
    else
      post_tag = tag.post_tags.find_by(post_id: self.id)
      post_tag.destroy if post_tag
    end
  end
end

 #accepts_nested_attributes_for :tags, allow_destroy: true

 # before_validation :downcase_tag_name
 # validates :tag_name, presence: true, uniqueness: { case_sensitive: false }

 def favorited_by?(user)
   favorite.exists?(user_id: user.id)
 end

 #検索メソッド、タイトルと内容をあいまい検索する
 def self.posts_serach(search)
   Post.where('text LIKE ?', "%#{search}%")
 end

 def save_posts(tag_list)
  # タグが存在していれば、タグの名前を配列として全て取得
   current_tags = self.tag.pluck(:tag_name) unless self.tag.nil?
  # 現在取得したタグから送られてきたタグを除いてoldtagとする
   old_tags = current_tags - tag
   # 送信されてきたタグから現在存在するタグを除いたタグをnewとする
   new_tags = tag - current_tags


   # 古いタグを消す
   old_tags.each do |old_name|
     self.tags.delete Tag.find_by(tag_name:old_name)
   end

   # 新しいタグを保存
   new_tags.each do |new_name|
     post_tag = Tag.find_or_create_by(tag_name:new_name)
     self.tag << tag
   end
 end

 def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("text LIKE?","#{word}")
    elsif search == "partial_match"
      @post = Post.where("text LIKE?","%#{word}%")
    else
      @post = Post.all
    end
  end

end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
  attr_accessor :tag_name
end

app/models/tag.rb
class Tag < ApplicationRecord
  #has_many :post_tag, dependent: :destroy
  #has_many :post, through: :post_tag

  validates :name, presence:true, length:{maximum:20}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :image
  
  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
  def user_status
    if is_deleted == true
      "✕"
    else
      "〇"
    end
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
  end
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
before_action :authenticate_admin!
  def show
    @post = Post.find(params[:id])
    @comments = @post.comment.all
    # @user = User.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "投稿を削除しました"
    redirect_to admin_users_path
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.page(params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page])
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  def after_sign_in_path_for(resource)
    case resource
    when User
      public_users_show_path
    when Admin
      admin_clothes_path
    end
  end
  
  def after_sign_out_path_for(resource)
    case resource
    when :user
      new_user_session_path
    when :admin
      new_admin_session_path
    end
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
end

app/helpers/admin/clothes_helper.rb
module Admin::ClothesHelper
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header style="background-color: #a0d8ef;">
      <nav class="navbar navbar-expand-lg navbar-white">
        <nav class="container">
          <!--いらないかもしれない-->
          <a class="navbar-brand p-3" href="/"><strong>clothes forcast</strong></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <% if request.fullpath.include? "/admin"%>
                <li class="nav-item p-3">
                  <%= link_to "服装一覧", admin_clothes_path %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "ユーザー一覧", admin_users_path %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete%>
                </li>
              <% else %>
                <li class="nav-item p-3">
                  <%= link_to "服装一覧", public_clothes_path %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "投稿一覧", public_posts_path %>
                </li>
                <li class="nav-iten p-3">
                  <%= link_to "マイページ", public_users_show_path %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
                </li>
              <% end %>
              <% elsif user_signed_in? %>
                <li class="nav-item p-3">
                  <%= link_to "服装一覧", public_clothes_path %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "投稿一覧", public_posts_path %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "マイページ", public_users_show_path %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </li>
              <% else %>
              <!--ビューページ作成後リンクを付ける-->
                <li class="nav-item p-3">
                  <%= link_to "新規登録", new_user_registration_path %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "ログイン", new_user_session_path %>
                </li>
                <li class="nav-item p-3">
                  <%= link_to "服装一覧" ,public_clothes_path %>
                </li>
              <% end %>
            </ul>
          </div>
        </nav>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>